name: docs-ci
on:
  pull_request:
    paths: ["**/*.md","docs/**","MANIFEST.sha256"]
jobs:
  lint-and-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: avto-dev/markdown-lint@v1
        with: { args: 'docs/*.md *.md' }
      - name: Build checksum manifest (validate)
        run: |
          ROOT=docs && [ -d docs ] || ROOT=.
          find "$ROOT" -maxdepth 1 -name "*.md" -type f -print0 |
          xargs -0 -I{} sha256sum "{}" | sort > MANIFEST.sha256.new
          if [ -f MANIFEST.sha256 ]; then
            diff -u MANIFEST.sha256 MANIFEST.sha256.new || echo "::warning ::MANIFEST.sha256 will be updated on merge"
          else
            echo "::notice ::MANIFEST.sha256 will be created on merge"
          fi
